import {Oglas} from "./oglas";

export const OGLASI: Oglas[] = [
  // {oglasId: 1, cijena: 5000, opis: "Jako dobar auto molim kupite troši previše benge", naslov: "Suzuki Swift 2010", kategorijaId: 1, imeProdavaca: "Luka", telefon: "0995084412", fotografije: "string", lokacija: "Zagreb" , imagePath: "https://maserati.scene7.com/is/image/maserati/maserati/regional/us/hero-website-new-upload/221340M_1920x1080.jpg?$1920x2000$&fit=constrain"},
  // {oglasId: 2, cijena: 1000000, opis: "Prodajem stan u voltinom, lokacija šibenska 2 ima malo rupa od potresa ali je lijepo radi zraka.", naslov: "Prodajem stan na trešnjevci", kategorijaId: 2, imeProdavaca: "Luka", telefon: "099602432", fotografije: "string", lokacija: "Zagreb" , imagePath: "http://kajzericagradjenje.hr/wp-content/uploads/slike-455-456_3.jpg"},
  // {oglasId: 3, cijena: 10, opis: "Laptop prodajem za kunu jer je toliko loš.", naslov: "Prodajem jako loš laptop.", kategorijaId: 3, imeProdavaca: "Luka", telefon: "099602432", fotografije: "string", lokacija: "Zagreb" , imagePath: "https://i2.wp.com/www.mopo.ca/wp-content/uploads/2010/04/broken_laptop01-520x390.jpg?resize=520%2C390"},
  // {oglasId: 4, cijena: 150, opis: "Jako dobar mobitel možda je star ali je lep.", naslov: "Samsung galaxy s7", kategorijaId: 3, imeProdavaca: "Luka", telefon: "099602432", fotografije: "string", lokacija: "Zagreb" , imagePath: "https://cdn.pocket-lint.com/r/s/970x/assets/images/136767-phones-review-samsung-galaxy-s7-edge-review-image1-hl9cn7gsdo.jpg"},
  // {oglasId: 5, cijena: 200, opis: "Pozz, našao sam nekog psa na ulici pa ga prodajem. Samo ozbiljni kupci molim vas zovite na 0995234234", naslov: "Prodajem pse", kategorijaId: 4, imeProdavaca: "Luka", telefon: "099602432", fotografije: "string", lokacija: "Zagreb" , imagePath: "https://media.istockphoto.com/photos/cute-happy-dog-playing-with-a-stick-picture-id1184184060?k=20&m=1184184060&s=612x612&w=0&h=bxEn6LtJBegPuSwsL9RlyPob-7Si6lLpnROvLadFaAg="},
  // {oglasId: 6, cijena: 10, opis: "Bok prodajem štakore samo ih morate uloviti u podrumu. LP", naslov: "Prodajem štakore", kategorijaId: 4, imeProdavaca: "Luka", telefon: "099602432", fotografije: "string", lokacija: "Zagreb" , imagePath: "https://lumiere-a.akamaihd.net/v1/images/open-uri20150422-20810-f3qxzs_4923c203.jpeg"}
]
